DROP TABLE USUARIOS_ROLES;
DROP TABLE ROLES;
DROP TABLE LISTAS_REPRODUCIBLES;
DROP TABLE LISTAS;
DROP TABLE TIPOS_LISTAS;
DROP TABLE CALIFICACIONES_REPRODUCIBLES;
DROP TABLE USUARIOS;
DROP TABLE REPRODUCIBLES_GENEROS;
DROP TABLE REPRODUCIBLES_PERSONAS;
DROP TABLE REPRODUCIBLES_PLATAFORMAS;
DROP TABLE TRAILERS_REPRODUCIBLES;
DROP TABLE GENEROS;
DROP TABLE PERSONAS;
DROP TABLE PLATAFORMAS;
DROP TABLE REPRODUCIBLES;
DROP TABLE SAGAS;

DROP DATABASE justtrack;